'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { ResponsiveContainer, ScatterChart, Scatter, CartesianGrid, XAxis, YAxis, Tooltip } from 'recharts';
import type { ModelSnapshot, ReasoningEffort } from '@/lib/types';
import { atEffort, effortLabels, efforts } from '@/lib/reasoning';
import { providerSymbols } from '@/lib/provider-symbols';
function Check({label,name,checked,onChange,partial=false}:{label:string,name?:string,checked:boolean,onChange:(checked:boolean)=>void,partial?:boolean}) {
  return <label className="check-chip"><input type="checkbox" aria-label={name||label} checked={checked} ref={node=>{if(node)node.indeterminate=partial;}} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;
}
export default function ModelExplorer({models,checkedEfforts,onEffortChange,colors}:{models:ModelSnapshot[],checkedEfforts:ReasoningEffort[],onEffortChange:(efforts:ReasoningEffort[])=>void,colors:Record<string,string>}) {
  const [families,setFamilies]=useState(Object.keys(colors));
  const [tiers,setTiers]=useState(['최상위','차상위','경량','미확인']);
  const [checkedModels,setCheckedModels]=useState<string[]>([]);
  const [metric,setMetric]=useState<'intelligence'|'coding'|'agentic'>('intelligence');
  const labels={intelligence:'종합 성능',coding:'코딩',agentic:'에이전트'};
  const filtered=models.filter(m=>families.includes(m.creator)&&tiers.includes(m.tier));
  const visible=filtered.filter(m=>!checkedModels.length||checkedModels.includes(m.modelId));
  const expanded=checkedModels.length>0;
  function toggleModel(id:string,checked:boolean) {const next=checked?[...checkedModels,id]:checkedModels.filter(x=>x!==id);setCheckedModels(next);onEffortChange(next.length?[...efforts]:['high']);}
  const levels=efforts.filter(e=>checkedEfforts.includes(e));
  const points=visible.flatMap(m=>levels.map(e=>atEffort(m,e)));
  function providerPoint(props:unknown) {
    const {cx,cy,payload}=props as {cx?:number;cy?:number;payload?:ModelSnapshot};
    if(cx===undefined||cy===undefined||!payload) return <g/>;
    const level=payload.reasoningEffort||'high';
    return <g className="provider-point" data-model={payload.modelId} data-provider={payload.creator} data-effort={level} transform={`translate(${cx},${cy})`}>
      <title>{payload.modelName} · {effortLabels[level]}</title>
      <circle r={level==='high'?5:3.5} fill={colors[payload.creator]} stroke="var(--surface)" strokeWidth={1.5}/>
    </g>;
  }
  const selectedLabel=levels.length===efforts.length?'전체':levels.length?levels.map(e=>effortLabels[e]).join(' · '):'없음';
  function reset() {setFamilies(Object.keys(colors));setTiers(['최상위','차상위','경량','미확인']);setCheckedModels([]);onEffortChange(['high']);}
  const sol=models.find(m=>m.modelId==='mini'); const astra=models.find(m=>m.modelId==='gpt');
  return <section className="section explorer" aria-labelledby="explorer-title">
    <div className="section-heading"><div><div className="eyebrow">MODEL × REASONING</div><h2 id="explorer-title">성능 vs. 가격</h2><p role="status">{points.length}개 점 · {expanded?`${visible.length}개 모델의 추론 ${levels.length}단계 비교`:'전체 모델 · High 기준'}</p></div><span className="badge">예시 수치 · 5단계 설정</span></div>
    <div className="explorer-controls check-controls">
      <fieldset className="check-group"><legend>제작사</legend>{Object.keys(colors).map(c=><Check key={c} label={providerSymbols[c].label+' ('+providerSymbols[c].symbol+')'} checked={families.includes(c)} onChange={checked=>setFamilies(prev=>checked?[...prev,c]:prev.filter(x=>x!==c))}/>)}</fieldset>
      <select aria-label="그래프 성능 지표" value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>
      <Check label="전체 45개 보기" checked={checkedModels.length===models.length&&levels.length===efforts.length} onChange={checked=>{setCheckedModels(checked?models.map(m=>m.modelId):[]);onEffortChange(checked?[...efforts]:['high']);}}/>
    </div>
    <div className="model-focus"><div className="focus-heading"><strong>추론량 펼쳐보기</strong><span>모델을 체크하면 Low → Ultra를 연결합니다.</span>{expanded&&<button className="text-link" onClick={()=>{setCheckedModels([]);onEffortChange(['high']);}}>High 전체로 돌아가기</button>}</div><fieldset className="check-group focus-models"><legend className="sr-only">추론량을 비교할 모델</legend>{filtered.map(m=><Check key={m.modelId} label={m.modelName.replace('GPT · ','').replace('Claude · ','').replace('Gemini · ','')} name={m.modelName} checked={checkedModels.includes(m.modelId)} onChange={checked=>toggleModel(m.modelId,checked)}/>)}</fieldset></div>
    <details className="model-check-details"><summary>세부 조건 <span>등급 · 추론 단계</span></summary><fieldset className="check-group tier-checks"><legend>등급</legend>{['최상위','차상위','경량','미확인'].map(t=><Check key={t} label={t} name={t+' 등급'} checked={tiers.includes(t)} onChange={checked=>setTiers(prev=>checked?[...prev,t]:prev.filter(x=>x!==t))}/>)}</fieldset>{expanded&&<fieldset className="check-group effort-checks"><legend>추론량</legend><Check label="전체" name="추론량 전체" checked={levels.length===efforts.length} partial={levels.length>0&&levels.length<efforts.length} onChange={checked=>onEffortChange(checked?[...efforts]:[])}/>{efforts.map(e=><Check key={e} label={effortLabels[e]} checked={levels.includes(e)} onChange={checked=>onEffortChange(checked?[...checkedEfforts,e]:checkedEfforts.filter(x=>x!==e))}/>)}</fieldset>}</details>
    <div className="explorer-layout"><div className="explorer-chart"><div className="axis-caption">↑ {labels[metric]} · 높을수록 우수</div><div className="decision-plot" role="img" aria-label={`${selectedLabel} 추론량의 ${labels[metric]}과 작업당 예상 비용. 아래 라인업 표에서 정확한 수치를 확인할 수 있습니다.`}><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:28,right:40,bottom:8,left:0}}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis type="number" dataKey="taskCost" name="작업당 비용" tickFormatter={v=>`$${Number(v).toFixed(3)}`} axisLine={false} tickLine={false} tick={{fontSize:11,fill:'var(--muted)'}}/><YAxis type="number" dataKey={metric} name={labels[metric]} domain={[60,100]} tick={{fontSize:11,fill:'var(--muted)'}} axisLine={false} tickLine={false} width={35}/><Tooltip cursor={{strokeDasharray:'3 3'}} content={({active,payload})=>active&&payload?.length?<div className="tooltip"><strong>{payload[0].payload.modelName}</strong><div>{payload[0].payload.tier} · 추론 {effortLabels[payload[0].payload.reasoningEffort as ReasoningEffort]}</div><div>{labels[metric]} {payload[0].payload[metric].toFixed(1)} · ${payload[0].payload.taskCost.toFixed(4)} / 회</div><div>추론 {payload[0].payload.reasoningTokens.toLocaleString()} 토큰 · 응답 {payload[0].payload.responseSeconds}초</div></div>:null}/>{visible.map((m,index)=><Scatter key={m.modelId} name={m.modelName} shape={providerPoint} fill={colors[m.creator]} line={expanded?{stroke:colors[m.creator],strokeWidth:1.5,strokeDasharray:index%2?'5 4':undefined}:false} lineType="joint" isAnimationActive={false} data={points.filter(p=>p.modelId===m.modelId)}/>)}</ScatterChart></ResponsiveContainer></div><div className="axis-caption axis-bottom">작업당 예상 비용 (USD) → <span>입력 1,000 + 답변 500 + 추론 토큰</span></div><div className="legend">{expanded?visible.map((m,index)=><span key={m.modelId}><i className={'model-line-key '+(index%2?'dashed':'')} style={{borderColor:colors[m.creator]}}/>{m.modelName}</span>):Object.entries(colors).filter(([name])=>visible.some(m=>m.creator===name)).map(([name,color])=><span key={name}><i style={{background:color}}/>{providerSymbols[name].label}</span>)}<span className="shape-key">{expanded?'작은 점 Low → Ultra · 큰 점 High':'점에 마우스를 올리거나 눌러 모델 확인'}</span></div></div>
    <aside className="decision-aside" aria-label="Sol과 Astra 비교"><div className="eyebrow">CHOICE SPOTLIGHT</div><h3>Sol, 아니면 Astra?</h3><p>{levels.length!==1?'요약은 중간 추론 기준':'동일 추론량의 성능·비용 비교'}</p><div className="spotlight-models">{[sol,astra].filter((m):m is ModelSnapshot=>!!m).map(m=><article key={m.modelId}><div><strong>{m.modelName.replace('GPT · ','')}</strong><span className="badge">{m.tier}</span></div><dl><div><dt>{labels[metric]}</dt><dd>{m[metric].toFixed(1)}<small>점</small></dd></div><div><dt>작업당 비용</dt><dd>${m.taskCost?.toFixed(4)}</dd></div><div><dt>예상 응답</dt><dd>{m.responseSeconds}<small>초</small></dd></div></dl></article>)}</div>{sol&&astra&&<p className="decision-summary">Astra는 Sol보다 {labels[metric]} {(astra[metric]-sol[metric]).toFixed(1)}점 높고, 비용은 {((astra.taskCost||0)/(sol.taskCost||1)).toFixed(1)}배입니다. <span>예시 비교</span></p>}<Link href="/compare" className="text-link">모델별 추론량을 다르게 비교<ArrowUpRight size={15}/></Link></aside></div>
    <div className="lineup-heading"><h3>제작사별 라인업</h3><span role="status">{points.length}개 설정 · 추론량 {selectedLabel}</span></div>{points.length?<div className="table-wrap" role="region" aria-label="모델 등급과 추론량별 지표" tabIndex={0}><table><thead><tr><th scope="col">모델 / 제작사</th><th scope="col">라인업 등급</th><th scope="col">추론량</th><th scope="col">{labels[metric]}</th><th scope="col">추론 토큰</th><th scope="col">예상 응답</th><th scope="col">작업당 비용</th></tr></thead><tbody>{[...points].sort((a,b)=>a.creator.localeCompare(b.creator)||(['최상위','차상위','경량','미확인'].indexOf(a.tier)-['최상위','차상위','경량','미확인'].indexOf(b.tier))).map(m=><tr key={m.modelId+'-'+m.reasoningEffort}><td><strong>{m.modelName}</strong><small className="creator-label">{m.creator}</small></td><td><span className={`badge ${m.tier==='최상위'?'new':''}`}>{m.tier}</span></td><td>{effortLabels[m.reasoningEffort||'medium']}</td><td>{m[metric].toFixed(1)}</td><td>{m.reasoningTokens?.toLocaleString()}</td><td>{m.responseSeconds}초</td><td>${m.taskCost?.toFixed(4)}</td></tr>)}</tbody></table></div>:<div className="empty"><h3>체크한 조건에 표시할 점이 없습니다</h3><p>제작사·모델·추론량을 하나 이상 체크하세요.</p><button onClick={reset}>그래프 필터 초기화</button></div>}<div className="table-note">등급·추론 설정·수치는 화면 검토용 예시입니다. 실제 지원 설정과 과금 방식은 제작사마다 다릅니다.<Link href="/methodology">계산 기준 보기<ArrowUpRight size={12}/></Link></div>
  </section>;
}
